server:
  port: 8090
  servlet:
    context-path: /

jwt:
  secret: ovvJmf9yQehvknlaS/Ni18rBmvj/2g+lNVOXES9eGqKI2DlF86y8pnSlDOT0P9A9 # <-- 48 байт для HS384
  expiration: 86400000 # 1 день в миллисекундах (long)

logging:
  level:
    ru.itis.dis403.lab2_6.config: DEBUG

spring:
  freemarker:
    suffix: .ftlh
    template-loader-path: classpath:/templates
    request-context-attribute: rc
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: 00000000
#    url: jdbc:postgresql://localhost:5432/lab02_06
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
  security:
    filter:
      dispatcher-types: REQUEST, ERROR, ASYNC

